name: "💂"

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: checkout changes
        uses: actions/checkout@v2

      - name: get commit info
        run: echo "SHA=$GITHUB_SHA" >> $GITHUB_ENV

      - name: prepare java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: prepare depdendency cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: '${{ runner.os }}-m2-${{ hashFiles(''**/pom.xml'') }}'
          restore-keys: '${{ runner.os }}-m2'

      - name: prepare git config
        run: git config --global user.name "CI Slave Bot"

      - name: patch paper
        run: ./paper patch

      - name: test
        run: mvn test --file pom.xml --batch-mode --errors --show-version
